DROP TABLE IF EXISTS User CASCADE;
CREATE TABLE User (
  userID SERIAL PRIMARY KEY,
  username VARCHAR(45),
  password CHAR(60) NOT NULL,
  email VARCHAR(45),
  phone BIGINT(10)
);

DROP TABLE IF EXISTS Item CASCADE;
CREATE TABLE Item (
  ItemId SERIAL PRIMARY KEY,
  ItemName VARCHAR(45) NULL,
  ItemDescription VARCHAR(200) NULL,
  Condition VARCHAR(200) NULL,
  CategoryID INT NULL,
  CONSTRAINT Cat
    FOREIGN KEY (CategoryID)
    REFERENCES Category (CategoryID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

DROP TABLE IF EXISTS Image;
CREATE TABLE IF NOT EXISTS Image (
  ImageID SERIAL PRIMARY KEY,
  URL VARCHAR(45) NULL,
  CategoryID INT NULL,
  CONSTRAINT Category
    FOREIGN KEY (CategoryID)
    REFERENCES Category (CategoryID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

DROP TABLE IF EXISTS ItemHistory;
CREATE TABLE ItemHistory (
  HistoricalOrderID SERIAL PRIMARY KEY,
  ItemID INT NOT NULL,
  userID INT NOT NULL,
  timeBorrowed DATETIME NULL,
  timeReturned DATETIME NULL,
  INDEX Item_idx (ItemID ASC) VISIBLE,
  CONSTRAINT userID
    FOREIGN KEY (userID)
    REFERENCES User (userID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT Item
    FOREIGN KEY (ItemID)
    REFERENCES Item (ItemId)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

DROP TABLE IF EXISTS Fee;
CREATE TABLE Fee (
  userID INT NOT NULL,
  HistoricalOrderID INT NOT NULL,
  amount DECIMAL(7,2) NULL,
  paid TINYINT NULL DEFAULT 0,
  payby DATE NULL,
  PRIMARY KEY (userID, HistoricalOrderID),
  INDEX ItemHistory_idx (HistoricalOrderID ASC) VISIBLE,
  CONSTRAINT User
    FOREIGN KEY (userID)
    REFERENCES User (userID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT ItemHistory
    FOREIGN KEY (HistoricalOrderID)
    REFERENCES ItemHistory (HistoricalOrderID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);




